---
openapi: 3.0.1
info:
  title: Pong API V1
  description: Ping API
paths:
  "/api/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
              required:
              - nickname
  "/api/users/{id}":
    patch:
      summary: Modifies an user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user modified
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
    get:
      summary: Retrieves an user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                "$ref": "#/definitions/user"
    delete:
      summary: Deletes an user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user deleted
          content: {}
servers:
- url: http://{defaultHost}:3000
  variables:
    defaultHost:
      default: localhost
definitions:
  errors_object:
    type: object
    properties:
      errors:
        "$ref": "#/definitions/errors_map"
  errors_map:
    type: object
    additionalProperties:
      type: array
      items:
        type: string
  user:
    type: object
    properties:
      id:
        type: integer
      avatar:
        type: string
      guild_id:
        type: integer
        nullable: true
      status_id:
        type: integer
      ladder_id:
        type: integer
      two_factor:
        type: boolean
      nickname:
        type: string
    required:
    - nickname
    - avatar
    - guild_id
    - status_id
    - ladder_id
    - two_factor
