Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Excludes:
    - db/**/*
    - config/**/*
    - script/**
    - bin/**
    - spec/**/*
    - vendor/**/*
Metrics/MethodLength:
  Max: 15
Metrics/ClassLength:
  Max: 102
