version: '3.0'
services:
  db:
    image: postgres:12.1
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secure
  web:
    build: .
    volumes:
      - ./server/:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PG_PASSWORD: secure