version: '3.0'
services:
  pg:
    image: postgres:12.1
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secure
  rails:
    build: .
    container_name: pong
    volumes:
      - ./server/:/app
    ports:
      - "3000:3000"
    depends_on:
      - pg
    environment:
      PG_PASSWORD: secure
      PG_USER: postgres
      PG_HOST: pg
