version: '3'
services:
  db:
    image: postgres:12.1
    environment:
        POSTGRES_PASSWORD: password # Needed for connections, choose user/password in config/database.yml
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - ./source:/myapp # Allow real time modifications
    ports:
      - "3000:3000"
    depends_on:
      - db
